import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :home_hub, HomeHubWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, :api_client, HomeHub.Finch

# Do not print debug messages in production
config :logger, level: :info

io_config = [fan_pin: 17, heater_pin: 27, dht_pin: 18]

config :home_hub, :thermostat,
  io_config: {HomeHub.Thermostat.IO, io_config},
  sensor_config: {HomeHub.Thermostat.TemperatureSensor, io_config}

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
